shopware/meteor

.github/workflows/update-icons.yml
=> NEXT-33446 - install puppeteer for update icon workflow

.gitignore
=> NEXT-33446 - add .env file to gitignore

packages/tokens/src/GenerateArtifacts.test.ts, packages/tokens/src/common/domain/file-system/InMemoryFileSystem.test.ts, packages/tokens/src/common/domain/utils/object.test.ts, packages/tokens/src/common/domain/utils/string.test.ts, packages/tokens/src/common/infrastructure/file-system/HardDiskFileSystem.test.ts, packages/tokens/src/deliverable/domain/CSSDeliverable.test.ts, packages/tokens/src/dictionary/domain/Color.test.ts, packages/tokens/src/dictionary/domain/Dictionary.test.ts
=> NEXT-33446 - get rid of facts

packages/icon-kit/package.json, pnpm-lock.yaml
=> NEXT-33446 - pin version of svg-autocrop to 1.1.1

.github/workflows/update-icons.yml
=> NEXT-33446 - fix puppeteer install in update icons workflow

packages/icon-kit/.gitignore
=> NEXT-33446 - ignore chrome installation folder

.gitignore, packages/icon-kit/.gitignore
=> NEXT-33446 - ignore chrome directory at the root of the repository

packages/admin-sdk/docs/docusaurus.config.js, packages/tokens/src/GenerateArtifacts.test.ts, packages/tokens/src/common/domain/file-system/InMemoryFileSystem.test.ts, packages/tokens/src/common/infrastructure/file-system/HardDiskFileSystem.test.ts, packages/tokens/src/dictionary/domain/Dictionary.test.ts
Changed the baseUrl configuration for the admin SDK docs.
This PR fixes the deployment for the admin SDK documentation. 
I changed the `baseUrl` in the docusaurus config to `/`, like suggested.
=> NEXT-33446 - update the baseUrl of docusaurus

.github/ISSUE_TEMPLATE/01-bug-report.yaml, CONTRIBUTING.md, README.md
This pull request adds more information about how to get started with contributing to the project. It also adds documentation on how to manage releases.
It makes it easier for new people to get started working on this project.
I updated the contribution guidelines and fixed the link to those guidelines in the
`README.md` file.
=> NEXT-33446 - improve getting started documentation

.changeset/eleven-apples-rush.md, packages/icon-kit/CHANGELOG.md, packages/icon-kit/package.json
I updated the changelog to use the new changeset workflow.
This way we can release the version update and do it through our new automated approach.
Removed the old changelog and replaced it with a changeset.
=> Prepare icon kit release

.changeset/config.json
=> allow changesets to publish public packages

.gitignore, packages/admin-sdk/package.json
=> Fix sdk package version

.changeset/tiny-colts-roll.md, packages/admin-sdk/src/channel.ts
Remove backwards compatible dataset call.
=> NEXT-33863 - Remove sdk backwards compatibility for datasets

packages/admin-sdk/docs/docs/guide/2_api-reference/ui/mainModule.md
Improvement for the Meteor Admin SDK Docs.
It was unclear that we have the method to add smartbar buttons to main modules.
Add extra heading and description for this feature.
=> NEXT-33666 - update docs for possibility to add smartbar components

packages/admin-sdk-example-app/package.json, pnpm-lock.yaml
This PR makes it possible again to install the dependencies for that project.
It was no longer possible to install the dependencies for that project.
I updated the pnpm-lock file.
Install the dependencies on your local machine.
=> update pnpm-lock.yaml file

.changeset/good-suns-run.md, packages/admin-sdk/package.json
=> NEXT-33690 - fix sdk exports

packages/admin-sdk/docs/docs/guide/4_concepts/component-sections.md, packages/admin-sdk/docs/docs/guide/4_concepts/locations.md
Wrong syntax used in the docs. Fixed it.
=> Use correct syntax for adding component sections

.changeset/plenty-meals-shake.md, packages/component-library/src/composables/useEmptySlotCheck.ts
The imported dependency was wrong
I think autocomplete. And this leads to dependency issues when using the library
Change it to Vue
=> Fix wrong react Fragment dependency

.github/workflows/visual-tests.yml, examples/nuxt-app/package.json, packages/admin-sdk/package.json, pnpm-lock.yaml
This PR fixes the jobs that use playwright. 
Playwright was not able to start because of some missing dependencies.
I added a new command before the playwright browser installation that install the dependencies needed to run the browsers.
It should be enough when the CI passes.
I also upgraded playwright to the latest version
=> Fix playwright installation in ci

examples/admin-sdk-app/package.json, examples/nuxt-app/package.json, packages/component-library/package.json, packages/tokens/package.json
- Add version to nuxt example app
- Sort packe json props
=> Fix package jsons

packages/component-library/README.md
I updated the README file of the Meteor components.
Makes it clear what steps to take when a developer decides to contribute to the component library.
* I removed the docker container stuff, because it no longer exists
* Updated the install command
* Updated the name of the commands to the new correct names
=> update component library documentation

.changeset/curly-cougars-reply.md, packages/admin-sdk/docs/docs/guide/2_api-reference/ui/menu.md
I am updating the documentation for `ui.menu`, the part is toggling menu.
The API is ready, but documentation is missing to guide people on how to use it.
N/A
N/A
N/A
N/A
=> PS-178 - Update the documentation for ui.menu

CONTRIBUTING.md
- Changed `npx changesets add` to `npx changeset add`
=> NTR - Update CONTRIBUTING.md

.changeset/rare-camels-itch.md, packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
Add tokens for checkbox component
This change brings our components closer to the design system.
I replaced the SCSS variables with our new tokens.
You can checkout the new styles trough the branch preview below.
=> NEXT-35643 - add tokens for checkbox component

.changeset/violet-carrots-watch.md, packages/component-library/src/components/form/mt-number-field/mt-number-field.interactive.stories.ts, packages/component-library/src/components/form/mt-number-field/mt-number-field.stories.ts, packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
=> Fix number field

.changeset/smart-coins-invite.md, packages/component-library/src/components/form/mt-select/mt-select.spec.ts, packages/component-library/src/components/form/mt-select/mt-select.vue
Fixing #221, which is blocking any falsy values like empty strings, `0`, `false`, ..
=> Fix mt select falsey values

packages/admin-sdk/src/in-app-features/index.ts
=> NEXT-37153 - Added pricing models

.github/workflows/npm-preview-release.yml, packages/component-library/package.json
This PR creates a new preview release for every branch.
This allows teams to no longer wait for a new release to test out new features or bug fixes.
I added a workflow that uses pkg.pr.new.
You can checkout the created package in the comment below.
=> ci: add continuous release job

.changeset/yellow-deers-join.md, packages/component-library/src/components/form/mt-button/mt-button.vue, packages/component-library/src/components/navigation/mt-segmented-control/mt-segmented-control.vue
I made use of the semantic border radius 
This allows us to theme the component library.
I replaced the primitive tokens with semantic tokens.
The visual tests should catch issues.
=> use button border radius token for button and segmented control

.changeset/seven-swans-buy.md, packages/component-library/src/components/form/mt-number-field/mt-number-field.interactive.stories.ts, packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
Make the buttons of the number field accessible.
This makes our components more inclusive.
I turned the elements, that increase or decrease the number value, into buttons.
You can check out the changes in the branch preview below.
I got rid of the SCSS and replaced it with plain CSS.
=> Make number field accessible

.devcontainer/devcontainer.json
Added a `.devcontainer` configuration
This removes the possibility of bugs caused by different dependencies like node and pnpm.
I added devcontainers config.
Install the Dev Containers extension and rebuild the project using devcontainers.
=> add devcontainer configuration

packages/component-library/src/components/icons-media/mt-icon/mt-icon.vue
Migrating the icon component over to the composition api.
This makes the component library a bit more modern.
I migrated the component over to the composition api.
The visual tests should catch issue, but feel free to check it yourself.
=> move icon composition api

.github/workflows/tests.yml
=> NEXT-37776 - Add ats job

examples/admin-sdk-plugin/src/Resources/app/administration/package.json, examples/admin-sdk-plugin/tests/acceptance/package.json
=> NEXT-37776 - Fix release

.github/workflows/tests.yml
=> Remove 6.6.7.1 run

.github/workflows/visual-tests.yml
=> fix comparison operators in ci

.github/workflows/visual-tests.yml
=> remove duplicate identifier in ci

packages/admin-sdk/package.json
Just updating the version of meteor to 5.6.0 so that I can publish the new version to npm
=> NEXT-36303 - Update version

examples/admin-sdk-plugin/tests/acceptance/tests/main-module.spec.ts
This PR fixes the Admin App SDK Acceptance Tests pipeline
The pipeline failed
I updated the selector to match the new HTML structure.
If the pipeline passes then everything is good to go.
=> ci: fix admin sdk pipeline

.changeset/spotty-beds-shave.md, packages/component-library/.stylelintrc.json, packages/stylelint-plugin-meteor/src/index.ts, packages/stylelint-plugin-meteor/src/package.json, packages/stylelint-plugin-meteor/src/prefer-color-token/index.ts, packages/stylelint-plugin-meteor/src/prefer-color-token/prefer-color-token.test.ts
I added this rule to make sure color tokens are used.
This rule allows us to drive the adoption of our color tokens.
I added a new rule that checks if a token or a global value is used if not then it reports the line.
I've added plenty of unit tests to make sure the rule works as intended.
Some global values like `initial` and `currentColor` are allowed.
=> Write rule for color property

.changeset/flat-dryers-rhyme.md, packages/component-library/.stylelintrc.json, packages/stylelint-plugin-meteor/src/index.ts, packages/stylelint-plugin-meteor/src/rules/prefer-font-token/index.ts, packages/stylelint-plugin-meteor/src/rules/prefer-font-token/prefer-font-token.test.ts
This rule checks every font value and reports violations.
To catch incorrect or improper uses of fonts 
The rule goes over each individual value and reports any violations.
I've written a few tests to check the rule works as expected
=> Add rule for font tokens

.changeset/rich-pugs-reply.md, packages/component-library/.stylelintrc.json, packages/stylelint-plugin-meteor/src/index.ts, packages/stylelint-plugin-meteor/src/rules/prefer-border-token/index.ts, packages/stylelint-plugin-meteor/src/rules/prefer-border-token/prefer-border-token.test.ts
This rule checks every border value and reports violations.
To catch incorrect or improper uses of border properties
The rule goes over each individual value and reports any violations.
I've written a few tests to check the rule works as expected
=> Add rule for borders

packages/component-library/src/components/form/_internal/mt-select-base/_internal/mt-select-result-list.vue, packages/stylelint-plugin-meteor/README.md
This PR updates the list of available rules for the plugin
This makes the documentation more accurate
I've updated the list of rules.
Proof-read
=> docs(stylelint-plugin-meteor): update list of rules

.github/workflows/tests.yml
We have some problems with the Acceptance Tests, we can't reproduce the issue locally. It only fails in the CI.
Until we found a solution we disable the tests.
I just commented out the code
=> ci: temporarily disable the acceptance test suite

.changeset/olive-cobras-approve.md, .changeset/rich-years-smile.md, .changeset/smart-hairs-tan.md, .changeset/tricky-turtles-smoke.md, .changeset/wise-fireants-invent.md, packages/component-library/src/components/form/mt-button/mt-button.spec.ts, packages/component-library/src/components/form/mt-button/mt-button.vue, packages/component-library/src/components/overlay/mt-tooltip/mt-tooltip.spec.ts
This PR adds a lot of unit tests for the `mt-button` component
This improves the stability and reduces the chance that we introduce breaking changes.
I just wrote a dozen of tests.
It should be enough that the unit tests pass.
While writing some tests I fixed some bugs I discovered during testing.
=> Add tests for the button component

packages/component-library/package.json, pnpm-lock.yaml
This PR upgrades all vitest related packages to the newest versions.
This way we keep up with the latest tech.
I've update all the vitest related packages.
If all tests pass then everything still works as it did before
=> build(component-library): upgrade several vitest packages

.changeset/tough-swans-cover.md, packages/component-library/package.json, packages/component-library/src/components/form/_internal/mt-field-error/mt-field-error.vue, packages/component-library/src/components/form/mt-email-field/mt-email-field.vue, packages/component-library/src/components/overlay/mt-tooltip/mt-tooltip.vue
Temporary placeholder PR for fixes in mt-text-field
During the integration of the mt-text-field in Shopware we encountered some issues which gets solved with this PR
=> fix: fix issues in mt-text-field

.changeset/little-moose-accept.md, docs/admin-sdk/docs/guide/2_api-reference/context.md, packages/admin-sdk/src/context/compare-version.spec.ts, packages/admin-sdk/src/context/compare-version.ts, packages/admin-sdk/src/context/index.ts
=> feat: rename compareShopwareVersion to compareIsShopwareVersion

packages/component-library/src/components/form/_internal/mt-base-field/mt-base-field.vue
This PR migrates the styles from SCSS to plain CSS.
This brings us one step closer to getting rid of SCSS.
I just migrated away from SCSS and to plain-old CSS.
If the visual tests pass everything is fine.
=> Migrate base field to css

packages/component-library/src/components/feedback-indicator/mt-toast/mt-toast.vue
This PR migrates the `mt-toast` over to plain css.
SCSS does not provide much, if even at all, value for us.
I migrated the SCSS to plain CSS.
If the visual tests pass everything is fine.
* I migrated the scss variables over to Design Tokens
=> Migrate mt toast over to plain css

packages/component-library/src/components/form/mt-slider/mt-slider.vue
This PR migrates the `mt-slider` over to plain css.
SCSS does not provide much, if even at all, value for us.
I migrated the SCSS to plain CSS.
If the visual tests pass everything is fine.
=> Migrate slider to plain css

packages/component-library/src/components/form/mt-datepicker/mt-datepicker.interactive.stories.ts
=> test(component-library): fix datepicker test

.changeset/fresh-turtles-deliver.md, docs/admin-sdk/docs/guide/2_api-reference/context.md, packages/admin-sdk/src/channel.ts, packages/admin-sdk/src/context/index.ts, packages/admin-sdk/src/message-types.ts
Adds the possibility to get the shopId used by the app system via admin sdk
=> feat: Add context.getShopId

docs/admin-sdk/docs/guide/2_api-reference/data/get.md, docs/admin-sdk/docs/guide/2_api-reference/data/subscribe.md, docs/admin-sdk/docs/guide/2_api-reference/data/update.md
Just notices some small things while preparing our US-Dev-Workshop
=> chore: improve admin-sdk documentation

packages/component-library/src/components/form/mt-email-field/mt-email-field.interactive.stories.ts, packages/component-library/src/components/form/mt-email-field/mt-email-field.stories.ts
Refactor the test
The test is flaky
Replace the spy with other solution
=> fix: flaky mt-email-field copy-to-clipboard button test

packages/component-library/src/components/form/mt-unit-field/mt-unit-field.spec.ts
Replacing the unit type import from convert-units
=> Fix: replace Unit type import

.github/ISSUE_TEMPLATE/03-accessibility-issue.yml
Update accessibility template in line with bug-report template
Change the input field to a textarea
An input field is quite small to describe the step to reproduce an issue
=> Update accessibility template in line with bug-report template

.changeset/loud-vans-learn.md, docs/admin-sdk/api-reference/ui/modals.md, packages/admin-sdk/src/message-types.ts, packages/admin-sdk/src/ui/modal/index.ts
https://github.com/shopware/shopware/issues/10414
Add the new method and implement the counterpart in platform.
https://github.com/user-attachments/assets/719d70d2-f558-4af0-b590-9aa9b85abe31
=> feat: add modal update functionality

packages/component-library/.storybook/test-runner.ts
This PR fixes the failing visual test on main.
The shadow indicates that there's something to scroll. 
I've made sure that there's no shadow when we show an empty state.
* I've removed a console.log call that gets called before every single test run
=> test(component-library): remove console log before every test run

.changeset/honest-islands-flow.md, packages/component-library/src/components/table-and-list/mt-data-table/mt-data-table.spec.ts, packages/component-library/src/components/table-and-list/mt-data-table/mt-data-table.vue
https://github.com/shopware/meteor/issues/859
=> feat: add slot for customizing table cell content
