shopware/meteor

- .gitignore
- packages/component-library/.storybook/ThemeProvider.ts
- packages/component-library/.storybook/preview.ts
- packages/component-library/package.json
- pnpm-lock.yaml
With this PR I enable the mechanisms to switch between dark and light mode components.
This change allows us to see a component in a dark and light mode. That makes it much easier to develop, and debug components for each color mode.
I achieved this by creating global decorator, that adds a `data-theme` attribute to the root element of the story.
Checkout the project and change the background colour by clicking in the picture / image icon.
https://github.com/shopware/meteor/assets/35109813/5e64e65b-4aa6-46fe-a6ff-9bf470edc25b
I also changed the colour of the backgrounds so they reflect the token values.
> set data-theme attribute depending on background of story

- packages/component-library/src/components/layout/sw-card/sw-card.stories.ts
- packages/component-library/src/components/layout/sw-card/sw-card.vue
I added design tokens to the `sw-card` component.
This makes the component support multiple themes.
I replaced the SCSS variables with CSS custom properties that use our Meteor Tokens.
You can use the preview branch to check the results
> implement tokens for sw-card component

- .changeset/tough-geckos-drum.md
- packages/admin-sdk/docs/docs/guide/2_api-reference/data/get.md
- packages/admin-sdk/docs/docs/guide/2_api-reference/data/subscribe.md
- packages/admin-sdk/docs/docs/guide/4_concepts/selectors.md
- packages/admin-sdk/src/_internals/data/selectData.spec.ts
- packages/admin-sdk/src/_internals/data/selectData.ts
- packages/admin-sdk/src/channel.ts
- pnpm-lock.yaml
Update the selectors in datasets to add more functionalities
The selectors in the datasets was using Lodash "get" and was very limited
Replace it with better alternative
See tests
> NEXT-33861 - improve selector

- .github/workflows/update-tokens.yml
This PR introduces another GitHub workflow to further automate the process of generating the Design Tokens.
This makes it easier for everyone to generate new tokens. Especially for designers as they lack the technical knowledge, but also for other developers as they just need to run that action. Otherwise they have to checkout the repository, install the dependencies, get and set the correct environment variables, running the script and creating a new PR.
I added a new GitHub workflow that one can trigger on the actions tab of the repository.
The only way to test it is by merging the changes and testing it manually.
> add github workflow to update tokens

- .github/workflows/update-tokens.yml
The update tokens workflow creates branches with a wrong branch name and branch title. If fixed it so it now matches the actual result of that action.
This separates the PRs created trough the update icon workflow from the ones created by the update tokens workflow.
I changed the configuration of the action that creates the PR.
Double check if the values are correct.
> update tokens workflow

- .github/workflows/release.yml
This PR enables [provenance](https://github.blog/2023-04-19-introducing-npm-package-provenance/) for our npm packages.
This increases trust for our packages, because we can be sure that the packages indeed published by us and not by a malicious person.
I've added a `NPM_CONFIG_PROVENANCE` environment variable to the CI pipeline. 
The changes will only have effect once this PR gets merged and we do another release.
Closes #63
> enable npm provenance

- .github/workflows/release.yml
This PR fixes the automatic release workflow. The action was able to create a new branch and push the changes to it. But it failed once it tried to create the PR.
We need this in order to make our automatic release workflow work again.
The job now has the permission to create a new pull request.
We'll see if it works once we merge this PR.
> add "pull request" write permission to release workflow

- packages/admin-sdk/docs/docs/guide/6_faq/index.md
Missing information about the Shopware version in the docs
> Add version information to docs

- .changeset/brave-bottles-build.md
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
Makes the size of the checkmark in the checkbox smaller.
Fixes a visual bug.
Removed the `size` property.
You can check it out in the deployment preview below.
Before: ![Bildschirmfoto 2024-04-02 um 14 13 45](https://github.com/shopware/meteor/assets/35109813/e83206cc-fe5c-4951-bc05-2a0a830469f9)
After: ![Bildschirmfoto 2024-04-02 um 14 13 48](https://github.com/shopware/meteor/assets/35109813/86013704-88bc-4c35-a793-8e9d05da3cdd)
> fix checkmark sizing in checkbox

- .changeset/shy-ladybugs-clap.md
- packages/component-library/src/components/navigation/mt-tabs/mt-tabs.vue
This PR improves the UX for the tab component by only animating the tab slider after the initial render.
Motion in design is used to convey meaning. The slider animation from one point to another helps the user understand from which tab we're coming from and to which one we're going. Adding this animation on the first render is confusing. Because it's not relevant from where we're coming.
After the component mounts the slider gets a CSS class that enables the animation.
You can check out the story in the deployment preview below.
> only animate tabs slider after first render

- .changeset/violet-eyes-sniff.md
- packages/admin-sdk/src/message-types.ts
- packages/admin-sdk/src/ui/menu/index.ts
I am adding the functionality to collapse the admin menu from an app.
Some app modules need a more extensive view, like Shopping Experiences.
Send a signal to collapse the admin menu from an app.
N/A
N/A
N/A
> PS-178 - Allow toggling the admin menu

- .changeset/purple-geckos-count.md
- packages/component-library/src/components/form/_internal/mt-base-field/mt-base-field.vue
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
- packages/component-library/src/components/form/mt-switch/mt-switch.vue
- packages/component-library/src/utils/uuid.ts
Fixes the id generation for the input fields.
This makes our app compatible with projects that use Nuxt or every other SSR framework.
We only set the id once the app hydrates the client. This prevents us from having a hydration miss-match. The only drawback with that is that the labels won't work when the user has Javascript disabled. As we currently don't practice progressive enhancement the whole app does not work without Javascript.
You can check out the nuxt example app and take a look at the console output.
I suggest that we use the [`useId`](https://github.com/vuejs/rfcs/issues/556) hook once Vue 3.5 is out.
> Fix UUID issue

- .changeset/warm-dolphins-talk.md
- packages/component-library/src/components/form/_internal/mt-select-base/mt-select-base.vue
- packages/component-library/src/components/form/mt-text-field/mt-text-field.vue
- packages/component-library/src/components/form/mt-textarea/mt-textarea.vue
- packages/component-library/src/components/form/mt-url-field/mt-url-field.stories.ts
- packages/component-library/src/components/form/mt-url-field/mt-url-field.vue
Classes on some form fields aren't rendered, e.g.  `<MtTextField class="foobar" v-model="username" />`
`inheritAttrs` was set to false
Remove attrs. Classes working again
> NEXT-34273 - fix class inheritance in form fields

- .changeset/many-coins-play.md
- packages/component-library/src/index.ts
The Popover component is already implemented in [storybook](https://meteor-component-library.vercel.app/?path=/docs/components-overlay-mt-popover--docs) but it's not imported to use [here](https://github.com/shopware/meteor/blob/main/packages/component-library/src/index.ts)
> Import popover component to use

- .changeset/soft-years-hope.md
- docs/admin-sdk/docs/guide/2_api-reference/context.md
- packages/admin-sdk/src/context/index.ts
- packages/admin-sdk/src/message-types.ts
I'm allowing Shopware apps to get the user's timezone.
Some applications need the user's timezone to calculate and display data based on it.
```ts
const userTimezone = await sw.context.getUserTimezone();
```
N/A
N/A
N/A
> NEXT-35973 - Allow getting user's timezone

- examples/nuxt-app/package.json
- packages/admin-sdk/package.json
- pnpm-lock.yaml
Updates the playwright versions in the project.
Fixes the pipeline. See https://github.com/shopware/meteor/actions/runs/9057602409/job/24884929132?pr=165
I upgraded the playwright versions.
I cherry-picked the commit that "caused" the failure, checked that it fixed the issue and then later removed the commit.
> Fix-failing-playwright-installation

- .changeset/spotty-carrots-worry.md
- packages/component-library/src/index.ts
Make floating-ui public available
Needed from the outside
Add to the exports
> NEXT-34293 - make floating-ui public available

- packages/component-library/.storybook/main.ts
Enables a11y plugin for storybook
I missed enabling it.
I added it to the storybook config.
> enable a11y plugin

- .changeset/violet-carrots-watch.md
- packages/component-library/src/components/form/mt-number-field/mt-number-field.interactive.stories.ts
- packages/component-library/src/components/form/mt-number-field/mt-number-field.stories.ts
- packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
The previous change in the number field would be breaking. Therefore I properly deprecated the change event and currently emit both `change` and `update:modelValue` until 5.0
> Deprecate number field change event

- .changeset/pretty-adults-grab.md
- packages/component-library/src/components/_internal/mt-label.vue
- packages/component-library/src/components/form/_internal/mt-select-base/_internal/mt-select-selection-list.vue
A fix for this issue: https://github.com/shopware/meteor/issues/199
Safari guy doesn't always trigger click events on non-interactive elements.
My fix is to make the span focusable and send a signal to Safari to trigger the click event.
> NTR - Fix tag deletion is not working on the Safari browser

- .changeset/young-parrots-talk.md
- packages/component-library/src/components/table-and-list/mt-pagination/mt-pagination.vue
I changed the design of the disabled pagination buttons.
Before this changes, it was not obvious that some buttons in for the pagination were disabled. This has now changed.
I added `cursor: not-allowed` and I also changed the background color of the disabled buttons.
You can see the changes in the branch preview below.
> PS-304 - improve styling of disabled pagination buttons

- packages/tokens/src/common/domain/utils/string.test.ts
- packages/tokens/src/common/domain/utils/string.ts
- packages/tokens/src/deliverable/domain/CSSDeliverable.ts
This PR improves the debugging experience when the script fails to generate a `CSSDeliverable`
Improves debugging information for when the script fails to resolve an aliased token
I print the path of the resolved alias token.
> Fix typo sync script

- .github/workflows/visual-tests.yml
There was an update with playwright and now the playwright install script does not work anymore.
This makes the visual tests pipeline work again.
I pinned the version playwright installs browser for.
When the visual test pipeline goes through everything is fine.
> Fix failing visual test pipeline

- .changeset/silly-tomatoes-allow.md
- packages/admin-sdk/src/data/composables/useSharedState.spec.ts
- packages/admin-sdk/src/data/composables/useSharedState.ts
The initial shared state value gets updated only after change. This is now fixed
Check if store value exists. If not, add the initialValue to it. If it is exists, use the value
See jest test adjustments
> NEXT-37155 - fix initial shared state value

- packages/tokens/src/deliverable/domain/CSSDeliverable.test.ts
- packages/tokens/src/deliverable/domain/CSSDeliverable.ts
This script fixes the token sync script. It allows us to sync non-string tokens.
This allows us to sync the new tokens for things like typography, sizing and border radius.
I allowed the dictionary to resolve tokens that contain string and number values.
I've written a unit test in TDD style for this change.
> NEXT-36817 - fix typo sync script

- .changeset/shy-dolphins-pay.md
- packages/admin-sdk/src/_internals/data/EntityCollection.ts
- packages/admin-sdk/src/_internals/serializer/criteria-serializer.spec.ts
- packages/admin-sdk/src/_internals/serializer/criteria-serializer.ts
- packages/admin-sdk/src/data/Criteria.spec.ts
- packages/admin-sdk/src/data/Criteria.ts
1.  I fixed some wrongly typed in admin-sdk (NEXT-36488) and added some missing aggregation types in Criteria.ts
2. I added a new title in Criteria so it's can be used for debugging
Example usage:
```ts
criteria.setTitle('fetchNewlyCreatedCustomers');
```
It's hard to distinguish different search requests, it can used for apps & platform to have better overview in network tab
Add title property in Criteria.ts.
I will create a following up MR in platform after this change is released.
Unit test
**Before:**
You can't quickly see the difference between search requests without reading the payload
**After**
The search requests now have a name
> NEXT-37183 - Allow set title for Criteria

- package.json
- packages/component-library/src/components/form/_internal/mt-select-base/_internal/mt-select-selection-list.vue
Fixing the wrapping issue for the select placeholder. [NEXT-37472](https://shopware.atlassian.net/browse/NEXT-37472)
It is causing to show a clipped placeholder in case the placeholder text is too long to fit
Add CSS in the input wrapper to expand to full width and make the placeholder text to wrap
1. Run Storybook locally and go to http://localhost:6006/?path=/docs/interaction-tests-form-mt-select--docs
2. remove the selected values and set the `placeholder` prop to a very long text
This PR also updates the package.json `packageManager` version to match the current `pnpm-lock.yaml` version
[NEXT-37472]: https://shopware.atlassian.net/browse/NEXT-37472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NEXT-37472 - Fix select-selection-list placeholder not wrapping issue

- packages/component-library/src/components/context-menu/mt-context-button/mt-context-button.vue
Sass compiler throws Deprecation Warning.
Because of Mixed declarations.
https://sass-lang.com/documentation/breaking-changes/mixed-decls/
*Not rly.*
We will create a few PRs in the following weeks, addressing small issues with other components in Vite/Nuxt env.
> fix: mixed declarations (sass)

- .changeset/clever-clocks-pull.md
- packages/component-library/src/components/navigation/mt-tabs/mt-tabs.vue
- packages/component-library/src/components/overlay/mt-modal/mt-modal.vue
Fixes warning in console `[Vue warn]: Extraneous non-emits event listeners (newItemActive) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. If the listener is intended to be a component custom event listener only, declare it using the "emits" option.` and eslint warning `'defineEmits' is defined but never used`.
> fix: console warnings

- .changeset/gorgeous-snakes-press.md
- packages/component-library/src/components/table-and-list/mt-pagination/mt-pagination.spec.ts
- packages/component-library/src/components/table-and-list/mt-pagination/mt-pagination.vue
We can click the "Next Page" and "Last Page" buttons even when the data table is empty.
https://meteor-component-library.vercel.app/?path=/story/interaction-tests-table-and-list-mt-data-table--visual-test-render-empty-state
Calculate the value of totalPages will be zero if totalItems is zero, which will lead to the value of isOnLastPage being false.
I add a max value as one in the case totalItems is zero.
Unit test
> fix: disable next and last page button in mt-pagination

- packages/tokens/src/deliverable/domain/CSSDeliverable.test.ts
- packages/tokens/src/deliverable/domain/CSSDeliverable.ts
- packages/tokens/src/dictionary/domain/Dictionary.test.ts
- packages/tokens/src/dictionary/domain/Dictionary.ts
- packages/tokens/src/figma/infrastructure/FigmaApi.ts
The script now resolves tokens recursively.
This is needed so we can have multiple layers of semantic tokens.
Instead of resolving tokens only one layer deep we do this recursively until it resolves to a valid value.
I've written some unit tests that should be enough
> Resolve tokens recursively

- packages/component-library/src/components/feedback-indicator/mt-toast/mt-toast.vue
- packages/component-library/src/components/overlay/mt-modal/sub-components/mt-modal-action.vue
- packages/component-library/src/components/overlay/mt-modal/sub-components/mt-modal-close.vue
- packages/component-library/src/components/overlay/mt-modal/sub-components/mt-modal-trigger.vue
It removes `defineProps` and `defineEmits` imports, [provided by @vue/compiler-sfc in script setup](https://vuejs.org/api/sfc-script-setup#defineprops-defineemits).
Because of compilation warning
```
WARN  [@vue/compiler-sfc] defineProps is a compiler macro and no longer needs to be imported.
WARN  [@vue/compiler-sfc] defineEmits is a compiler macro and no longer needs to be imported.
```
By removing such imports.
> fix: remove @vue/compiler-sfc warning

- packages/component-library/src/components/overlay/mt-modal/mt-modal.vue
Removes the SCSS from the modal component.
This gets us closer to the goal of getting rid of SCSS.
I replaced the SCSS with plain css.
The visual tests should catch everything.
This PR has no changelog because it's only a refactor and does not have any effect on users of this package.
> remove scss from modal

- .changeset/dirty-rules-live.md
- packages/component-library/src/components/form/mt-number-field/mt-number-field.interactive.stories.ts
- packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
This MR fixes the issue in the sw-number-field component when pressing the up or down arrow keys if a new value was typed.
Before the fix, when the user types some value in a number field and after pressing the arrow up key or arrow down key, the new value is incorrect.
The solution was to update the internal value on any key input. This way when the arrow keys are pressed, the actual value is there.
Test cases were added
To manually testing:
1. Go to components-form-mt-number-field--docs
3. Focus in the input and type some number
4. Without moving the focus from the field press arrow up or arrow down.
> NEXT-37979 - Fix  input arrow up and down issue

- .changeset/rich-fireants-attend.md
- packages/component-library/src/components/layout/mt-card/mt-card.vue
This PR deprecates the hero property of the card component
It's used nowhere. 
I deprecated the property.
> deprecate hero card

- .changeset/gentle-goats-shop.md
- packages/component-library/.storybook/preview.ts
- packages/component-library/src/components/theme/mt-theme-provider.vue
- packages/component-library/src/composables/useFutureFlags.ts
- packages/component-library/src/index.ts
This PR adds a `mt-theme-provider` component. With this component we're able to configure the design system as a whole or only for parts of the application by placing the theme provider lower in the DOM tree.
Having future flags allows us to ship features early. Teams and users than can test out the features on their projects and give feedback. They're also able to incrementally migrate to new features without breaking the application.
```vue
<template>
<mt-theme-provider>
</mt-theme-provider>
</template>
```
Test it on your local machine. Instructions are in the "How" section.
Right now we do not provide any future flags, but we have some planned for the 4.0.0 release.
> add theme provider

- packages/component-library/src/components/layout/mt-card/mt-card.vue
This pr deprecates the `large` property of the card component.
Components should almost never have a max-width set by themselves. The parent element should
be responsible for doing that.
I deprecated the property.
> Deprecate large prop of card

- .changeset/soft-chicken-applaud.md
- docs/admin-sdk/docs/guide/2_api-reference/ui/mainModule.md
- packages/admin-sdk/src/message-types.ts
- packages/admin-sdk/src/ui/main-module/index.ts
Allow toggling page smart bar.
Some modules need a wider view.
N/A
N/A
N/A
> Allow toggling page smart bar

- packages/component-library/src/components/layout/mt-card/mt-card.vue
Removed some unnecessary css.
Reduces bundle size and make code more maintainable.
Removed some unused css.
Visual tests should catch issues.
> remove unnecessary card styling

- .changeset/chatty-shirts-think.md
- packages/component-library/src/components/layout/mt-card/mt-card.vue
- packages/component-library/src/composables/useFutureFlags.ts
I've added a new future flag to toggle the max-width behavior of cards.
The max width of the card component has been deprecated. To enable an easier transition to the new behavior people are able to switch to the new behavior before we make the breaking change.
I've added a new future flag.
The project can decide wether they want to adapt the new feature early or not.
To do that they need to add the `mt-theme-provider` component and enable the `removeCardWidth` flag like this:
```vue
<template>
<mt-theme-provider :future="{ removeCardWidth: true }">
</mt-theme-provider>
</template>
```
By default the old behavior is applied, but you can decide to change it by editing the them config via the `mt-theme-provider` component
> add future flag to remove card max width

- .changeset/smart-cobras-boil.md
- packages/component-library/src/components/navigation/mt-tabs/mt-tabs.vue
I deprecated the `small` property.
Elements should not set their max-width on their own. This is the job of the container element.
I marked the property as deprecated
No testing possible
> deprecate small prop on tab component

- .changeset/warm-plants-move.md
- packages/component-library/src/components/form/mt-datepicker/mt-datepicker.interactive.stories.ts
- packages/component-library/src/components/navigation/mt-tabs/mt-tabs.vue
- packages/component-library/src/composables/useFutureFlags.ts
This PR adds a future flag for adding the default margin.
Components should work in isolation. Adding a default margin to every component breaks that concept. Having a default margin ties the component to a specific context that it should work in. Once the component is used outside of that context you have to work around it. Make modifications to that component i.e. remove the default margin from the component. 
That new behavior is how every other component library out there does it. There's no default bottom margin for that component. If you want to add some space between the components you have to do that through the parent component or add a custom class on top of that component to add some spacing.
I've added a new future flag. By default it is disabled. But if you want you can …
> Add future flag for no default margin

- .changeset/strange-ducks-learn.md
- packages/component-library/src/components/layout/mt-card/mt-card.vue
This PR removes the default margin from the card component.
Components should not have margin set by themselves. The parent component should always take care of spacing elements.
The default margin will only be removed when the `removeDefaultMargin` flag is enabled.
Add a `mt-theme-provider` component and enable the `removeDefaultMargin` flag
> remove default margin from card

- packages/component-library/src/components/icons-media/mt-avatar/mt-avatar.spec.ts
- packages/component-library/src/components/icons-media/mt-avatar/mt-avatar.vue
I moved the `mt-avatar` component over to plain CSS.
This helps us to get rid of SCSS.
Migrated the SCSS over to CSS.
I've written some tests for the component, but feel free to test it yourself.
* I've added some tests for the `mt-avatar` component
* I've moved the component over to the composition api
> Migrate avatar to plain css and composition api

- .changeset/smooth-bees-smash.md
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
This PR removes the default margin from the checkbox component.
The parent component should take care of spacing elements. Not the component itself.
I've removed the default margin depending on whether or not the `removeDefaultMargin` future flag is activated or not.
The visual tests should catch issues. But feel free to test it yourself by checking out the story for the checkbox.
> remove default margin from checkbox

- .changeset/ninety-hairs-reflect.md
- .changeset/violet-books-kick.md
- packages/component-library/src/components/feedback-indicator/mt-loader/mt-loader.vue
This PR migrates the mt-loader component over to the composition api. It also gets grid of the SCSS and replaces it with plain css.
This gets us a step closer to getting rid of SCSS. Also, we modernize the component library by moving over to the composition api.
Got rid of the SCSS and replaced it with plain CSS.
The visual tests should catch issues.
> Migrate loader component

- .changeset/tender-llamas-sleep.md
- packages/component-library/src/components/form/_internal/mt-base-field/mt-base-field.vue
This PR remove the default margin for the base field and therefore for many of the form elements.
The parent component should always take care of spacing elements, not the element itself.
The default margin gets removed when the `removeDefaultMargin` future flag is enabled.
The visual tests should catch every issue, but feel free to test it out yourself using the branch preview below.
> remove default margin from base field

- packages/component-library/src/components/table-and-list/mt-pagination/mt-pagination.vue
This PR migrates the pagination over to plain css.
This brings us a step closer to getting rid of SCSS.
I replaced the SCSS with CSS.
The visual tests should catch issues. Feel free to test it yourself.
> migrate pagination over to plain CSS

- packages/component-library/src/components/feedback-indicator/mt-skeleton-bar/mt-skeleton-bar.vue
This PR migrates the skeleton component over to plain css.
This brings us a step closer to getting rid of SCSS.
Replaced the SCSS with plain CSS.
The visual tests should catch issues.
I've also enabled scoped css for this component.
> migrate skeleton over to plain css

- packages/component-library/src/components/feedback-indicator/mt-toast/mt-toast-notification.vue
This PR removes the SCSS of the `mt-toast` notification and replaces it with plain css.
This brings us a step closer to getting rid of plain css.
Replaced the SCSS with plain CSS.
The visual tests will catch issues if something looks different from how it's supposed to look like.
> move toast over to plain css

- packages/component-library/src/components/feedback-indicator/mt-banner/mt-banner.interactive.stories.ts
- packages/component-library/src/components/feedback-indicator/mt-banner/mt-banner.vue
This PR migrates the `mt-banner` component over to the composition api.
This brings us a step closer to modernizing the application.
I migrated the component over to the composition api.
The visual tests should catch issues.
No changelog because there are not changes on the user facing side.
> move banner over to composition api

- packages/component-library/src/components/theme/mt-theme-provider.vue
- packages/component-library/src/composables/useI18n.spec.ts
- packages/component-library/src/composables/useI18n.ts
I added a custom built `useI18n` composable for translating text.
Right now apps are forced to install the i18n plugin and configure it by themselves.
I added a new useI18n hook that will be used by the components. You can toggle the locale by setting the `locale` prop on the `mt-theme-provider` component.
I've written some unit tests that make sure the composable works as intended.
> add useI18n composable

- .changeset/curvy-walls-dress.md
- packages/component-library/src/components/form/mt-url-field/mt-url-field.vue
This PR deprecates the `mt-url-field`
This component is not really used anywhere. The same functionality can also be achieved by wrapping the text component and adding a suffix.
I deprecated the component.
There's no need for testing.
> deprecate mt-url-field component

- .changeset/gentle-plants-flash.md
- packages/component-library/src/components/form/mt-external-link/mt-external-link.vue
I deprecated the mt-external link
This component is no longer needed as we have another `mt-link` component. That component can do the same things this component can do.
I added a deprecation.
The visual tests will catch issues, but feel free to test it yourself.
* I add a notification that the default value for the `as` property will be `a` instead of `router-link`
> Deprecate mt-external link component

- packages/component-library/src/components/navigation/mt-search/mt-search.vue
This PR migrates the `mt-search` over to the composition api.
This brings us a step closer to modernizing the component library.
I migrated the component over to the composition api.
Our interaction tests should catch issues. But feel free to check the changes yourself.
> migrate mt-search over to composition api

- .changeset/chilled-apricots-grab.md
- packages/component-library/src/components/feedback-indicator/mt-banner/mt-banner.vue
This PR adds some translations for the mt-banner component.
They were missing.
I've made use of the new `useI18n` composable.
You can test the changes yourself by swapping out the locale of the `mt-theme-provider` you can find it inside the `preview.ts` file
> add translation for mt-banner

- packages/component-library/src/components/form/_internal/mt-field-copyable/mt-field-copyable.vue
I've migrated the component over to the composition api and the new usei18n composable.
The `vue-18n` package makes setting up the component library much harder. This custom built one makes it easier.
I've migrated the component from the vue-i18n package to the custom built useI18n composable.
Feel free to test it yourself.
> Migrate mt-field-copyable to custom i18n

- packages/component-library/src/components/form/_internal/mt-inheritance-switch/mt-inheritance-switch.vue
I've migrated the component over to the composition api and the new usei18n composable.
The `vue-18n` package makes setting up the component library much harder. This custom built one makes it easier.
I've migrated the component from the vue-i18n package to the custom built useI18n composable.
Feel free to test it yourself.
> Migrate mt-inheritance-switch to custom i18n

- packages/component-library/src/components/form/mt-password-field/mt-password-field.vue
I've migrated the component over to the composition api and the new usei18n composable.
The `vue-18n` package makes setting up the component library much harder. This custom built one makes it easier.
I've migrated the component from the vue-i18n package to the custom built useI18n composable.
Feel free to test it yourself.
> migrate mt-password-field to custom i18n

- .gitignore
I added the `.pnpm-store` folder to the `.gitignore`
We do not need, and should, commit this directory. It's used by pnpm to optimize the dependency installation process.
I added the file to the `.gitignore` file
Feel free to create the directory by hand on your machine and see if git ignores it.
> ignore .pnpm-store

- packages/component-library/src/components/overlay/mt-tooltip/mt-tooltip.vue
Changes the default `placement` of the tooltip to `top`
In most cases the tooltip will appear above the element.
I changed the `placement` property to `top`
Adding an automated test does not provide much value here.
> change default placement of tooltip to top

- .changeset/sour-chicken-juggle.md
- packages/component-library/.stylelintrc.json
- packages/stylelint-plugin-meteor/package.json
- packages/stylelint-plugin-meteor/src/index.ts
- packages/stylelint-plugin-meteor/src/rules/no-primitive-token/application/TokenGateway.ts
- packages/stylelint-plugin-meteor/src/rules/no-primitive-token/index.ts
- packages/stylelint-plugin-meteor/src/rules/no-primitive-token/infrastructure/InMemoryTokenGateway.ts
- packages/stylelint-plugin-meteor/src/rules/no-primitive-token/infrastructure/TokenGatewayUsingImport.ts
- packages/stylelint-plugin-meteor/src/rules/no-primitive-token/no-primitive-token.test.ts
- packages/tokens/package.json
- pnpm-lock.yaml
I've added a rule that reports any usage of primitive tokens.
Primitive tokens provide much less value compared to semantic design tokens. To prevent devs from using primitive tokens we report that to them in their IDE.
This rule gets the dictionary of the `@shopware-ag/meteor-tokens` package. And checks a forbidden primitive token is used.
I've written a handful of test to make sure the rule works as expected. The only thing that is not possible/very hard to test is the `TokenGatewayUsingImport` as there is much more setup involved.
This rule makes an exception for spacing tokens, those are primitive tokens and they're allowed to be used.
> feat(stylelint-plugin-meteor): add no primitive token rule

- .changeset/dry-pumpkins-try.md
- .changeset/flat-crews-call.md
- packages/stylelint-plugin-meteor/src/rules/prefer-sizing-token/index.ts
- packages/stylelint-plugin-meteor/src/rules/prefer-sizing-token/prefer-spacing-token.test.ts
This PR updates the auto-fixer of the `prefer-spacing-token` rule to update each value individually for properties like those:
`margin: 4px 8px` -> `margin: var(--scale-size-4) var(--scale-size-8)`
This allows us to migrate to the tokens much quicker
I've updated the autofixer to fix every individual value
Can only be merged after #410 got merged
> Add autofixer for shorthand spacing properties

- .changeset/clever-glasses-film.md
- packages/component-library/src/index.ts
I exported the `mt-tooltip` component so it's available to other projects.
This component is needed by other projects.
I added it to the `src/index.ts` file
Just proof-read it
> feat: export mt-tooltip

- .changeset/tasty-hairs-care.md
- .changeset/tricky-clouds-invite.md
- .changeset/wild-apples-smoke.md
- examples/admin-sdk-app/package.json
- examples/admin-sdk-plugin/src/Resources/app/administration/package.json
- examples/nuxt-app/package.json
- packages/component-library/package.json
- packages/component-library/src/components/feedback-indicator/mt-loader/mt-loader.vue
- packages/component-library/src/components/form/_internal/mt-select-base/_internal/mt-select-result-list.vue
- packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
- packages/component-library/src/components/overlay/mt-tooltip/mt-tooltip.vue
- packages/component-library/src/directives/popover.directive.ts
- packages/component-library/tsconfig.vitest.json
- pnpm-lock.yaml
This PR bumps the Vue version for the component library up to v3.5
Upgrading to Vue 3.5 allows us make use of new Vue features, which make things easier.
I've upgraded all Vue version to 3.5
Feel free to test it yourself on your local machine.
* Intentionally supressed some issues because it's planned to either remove those directives or re-write those components
* Vue is now a peer dependency, people are able to choose their own Vue version
> Upgrade to vue 3.5

- packages/stylelint-plugin-meteor/src/rules/prefer-sizing-token/index.ts
- packages/stylelint-plugin-meteor/src/rules/prefer-sizing-token/prefer-sizing-token.test.ts
This PR changes the rule to ignore negative spacing values
It does not make sense to report negative spacing values. 
I've updated the rule to exclude negative spacing values.
I've added some test to make sure the changes work as expected
> fix: allow negative spacing values

- .changeset/shy-ears-sort.md
- packages/component-library/package.json
- packages/component-library/src/components/_internal/mt-floating-ui/mt-floating-ui.vue
- packages/component-library/src/components/_internal/mt-priority-plus-navigation.vue
- packages/component-library/src/components/form/mt-select/mt-select.vue
- packages/component-library/src/components/form/mt-text-editor/mt-text-editor.vue
- packages/component-library/src/components/overlay/mt-tooltip/mt-tooltip.vue
- packages/component-library/src/utils/format.ts
- packages/component-library/vite.config.ts
- pnpm-lock.yaml
Several components don't have TS type information anymore.
There were issues in the generation of the types. 
Update to latest vite-plugin-dts and the latest vue-tsc. Then fixing all new TS type issues. Now they are generated again.
> fix: type generation for some components are now working again

- packages/component-library/tsconfig.app.json
- packages/component-library/tsconfig.vitest.json
This PR add the types for the jest-dom matchers.
The types for the jest-dom matchers were missing. Typing `.toBeInTheDocument` resulted in an type-error.
I updated the tsconfig so they no longer are overriting each other.
Check out the branch and test it yourself
> build(component-library): update tsconfig to include jest-dom types

- .changeset/slimy-cameras-joke.md
- packages/component-library/src/components/form/mt-switch/mt-switch.spec.ts
- packages/component-library/src/components/form/mt-switch/mt-switch.vue
Add aria attributes to mt-switch 
Mt-switch was lacking aria attributes which improve the accessibility experience for users 
Added aria-checked, aria-label and role to input element inside mt-switch
> UX-59 - add accessibility state labels to switch component

- .github/copilot/custom-instructions/test-style-guide.md
- .vscode/settings.json
- packages/component-library/package.json
- pnpm-lock.yaml
I added some custom instructions to improve the experience when generating tests with GitHub Copilot
This drastically improves the quality of GitHub Copilot's suggestions when generating tests.
I added a Markdown file with instructions and mentioned that file in the `.vscode/settings.json` file
Try it out
> Add custom instructions

- .github/workflows/visual-tests.yml
This PR fixes the visual test pipeline when someone starts it by creating a fork.
The pipeline failed because of the old configuration, this only happened with forks.
I just removed the `ref`
If the pipeline passes everything works.
> ci: fix failing visual test workflow for forks

- .changeset/beige-otters-protect.md
- packages/component-library/src/index.ts
I made the `mt-search` component public.
This project is used in some components like the core Shopware 6, where it's used inside card headers a lot.
I exported the component in the `src/index.ts` file
Check out the branch and test it out yourself.
> feat(component-library): make mt-search component public

- .changeset/green-kangaroos-deny.md
- packages/component-library/src/components/navigation/mt-tabs/mt-tabs.vue
I adjusted the size of the icon in `mt-tabs`
It was a visual but, the icon was way to huge.
Instead of sizing the icon via css I did it by setting the `size` prop of the `mt-icon` component
If the visual tests pass everything works as expected.
> fix(component-library): fix huge error badge in tabs component

- .changeset/spotty-singers-notice.md
- packages/component-library/src/components/context-menu/mt-context-button/mt-context-button.vue
- packages/component-library/src/components/context-menu/mt-context-menu.spec.ts
- packages/component-library/src/components/feedback-indicator/mt-progress-bar/mt-progress-bar.vue
This PR replaces the hard-coded spacing values with spacing tokens.
Using spacing tokens helps us to use consistent spacing across all our products.
I replaced the hard-coded spacing values with spacing tokens.
If the visual tests pass everything is the same as before.
> refactor(component-library): use spacing tokens in mt-progress-bar

- .changeset/rich-pots-tease.md
- packages/component-library/src/components/form/mt-number-field/mt-number-field.spec.ts
- packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
I fixed a bug were users were able to edit the value of a number field with a linked inheritance.
User should not be able to edit input fields with linked inheritance. To do so they must first unlink the inheritance.
I disabled the input field and the buttons to increment and decrement the value.
I wrote a couple of tests to make sure the bug is fixed.
To manually test it, check out the branch preview and set `isInherited` and `isInheritanceField` to true.
Now try changing the value, it won't be possible, which is the correct behavior.
I also added some visual tests to make sure the number field with linked inheritance looks like it should
> fix(component-library): prevent user from changing value of number field with linked inheritance

- docs/admin-sdk/docs/guide/1_getting-started/installation.md
- docs/admin-sdk/docs/guide/2_api-reference/location.md
Update the documentation
The handling for using iFrames inside plugins in the administration changes with 6.7 upwards and Vite
> docs: update docs for 6.7 instructions for the sdk

- .changeset/fluffy-teachers-complain.md
- docs/admin-sdk/docs/guide/2_api-reference/context.md
- packages/admin-sdk/src/context/index.ts
- packages/admin-sdk/src/message-types.ts
Added a new feature `contextShopwareVersion` to meteor SDK
To enhance the version comparison functionality by supporting versions that have four numeric parts and suffixes.
- Added `contextShopwareVersion` sender to the context SDK.
> feat: add `contextCompareShopwareVersion` to SDK

- .changeset/ten-dolls-film.md
- packages/component-library/src/components/form/_internal/mt-field-error/mt-field-error.vue
- packages/component-library/src/components/form/mt-email-field/mt-email-field.spec.ts
- packages/component-library/src/components/form/mt-email-field/mt-email-field.vue
This improves the a11y. When the user focuses the input field, the screen reader announces the error after it announces the label and the value of the input.
This way, screen reader users know when an input field has en error.
I added an `aria-invalid` label to the input fields
This only works with manual testing:
1. Checkout the branch preview
2. Go to a story with an invalid input field
3. Start your screen reader and see if it tells you that the input field is a) invalid and b) it announces the text of the error
> announce email field as invalid to screen readers when input has error

- .changeset/nine-cooks-clap.md
- packages/component-library/src/components/overlay/mt-modal/mt-modal.vue
There was a bug where, when the user opened the modal they could see a shadow, indicating that they can scroll inside the modal, which they could not because there was nothing to scroll.
I changed this so that it is no longer the case. The modal no longer shows a scroll shadow if the user cannot scroll inside the modal.
It does not make sense to show a scroll shadow. The job of it is to indicate that something is scrollable, but nothing is scrollable, show we should not show it.
When the modal gets closed we hide all scroll shadows. 
I did not write any unit tests as this is a visual feature and those are hard to test with unit tests.
So please do some manual testing:
1. Checkout the branch preview
2. Open a `mt-text-editor` story, click on the link icon in the toolbar
3. Check if the …
> do not show bottom shadow when content is not scrollable

- .changeset/thick-ligers-mix.md
- packages/component-library/src/index.ts
With this PR we make the `interface Toast` from `components/feedback-indicator/mt-toast/mt-toast.vue` available outside of the component library.
Right now, the `interface`  cannot be used when working with the `MtToast` component.
> chore: Export type Toast so that it can be used when working with MtToast components

- .github/workflows/npm-preview-release.yml
This fixes the failing preview build job by installing corepack via npm
The actions/setup-node@v4 action fails because it cannot correctly use corepack.
To fix that I implemented workaround. It installs corepack via npm and then enables it.
We cannot remove it, because pkg.pr.new needs corepack in order to work.
The job now installs `corepack` via npm and then enables it.
In order to test that, we need to create a preview build. To start that preview build
one person needs to approve this PR.
See: https://github.com/actions/setup-node/issues/1222#issuecomment-2631024706
> ci: enable corepack in npm preview build

- .changeset/pretty-drinks-check.md
- packages/component-library/src/components/_internal/mt-popover-deprecated/mt-popover-deprecated.vue
- Previously the `mt-popover-deprecated` component was configured to have the name `MtPopover`. This caused issues with some compiler setups. Change the name to `MtPopoverDeprecated`.
> fix: Deprecated popover

- .changeset/pink-planets-taste.md
- packages/component-library/src/index.ts
Made the `mt-url-field` component public, which is not exported by default currently.
> feat(component-library): make mt-url-field component public

- .changeset/fifty-pugs-beam.md
- .changeset/old-chicken-bathe.md
- packages/component-library/src/components/form/mt-colorpicker/mt-colorpicker.interactive.stories.ts
- packages/component-library/src/components/form/mt-colorpicker/mt-colorpicker.spec.ts
- packages/component-library/src/components/form/mt-colorpicker/mt-colorpicker.vue
I added a placeholder prop to the `mt-colorpicker` component.
Every input field can have a placeholder text. The same should be true for the colorpicker.
Before adding the feature I wrote a failing test. I then added the placeholder.
I've written a test to make sure the input field has the correct placeholder.
* I also added a missing link between the label and the input field. Now, when the user clicks on the label of the color picker the browser will focus the input field
> Add placeholder to colorpicker

- packages/component-library/README.md
I think the readme contains some old way of importing the styles of the component library. This should be correct now.
> docs: update css import guide in docs

- .changeset/late-dots-shop.md
- packages/tokens/README.md
I removed the early development warning for the token package.
We now use it for a while and it's pretty stable.
I updated the `README.md` file
> docs(tokens): remove early development warning for token package

- .changeset/smart-poems-remember.md
- packages/component-library/src/components/content/mt-text/mt-text.spec.ts
- packages/component-library/src/components/content/mt-text/mt-text.vue
I added some auto-completion for the `mt-text` component.
Makes it easier for people to use the text component.
I updated the types to include the literal types for the color tokens.
Use the `mt-text` component and set a value of the `color` prop. If you get autocompletion, then everything works as expected.
> Improve text component

- .changeset/green-onions-accept.md
- packages/component-library/src/components/form/mt-button/mt-button.vue
- packages/icon-kit/tsconfig.json
This PR allows developers to position their buttons.
It does not make sense to remove the margin of a button, because by default it does not have any.
It also causes issues when developers want to layout their buttons using margin.
I just removed the `margin: 0` declaration from the `mt-button` class.
> allow setting a margin on an mt-button component

- .github/dependabot.yml
Configure dependabot to upgrade all Tiptap packages at once.
When the tiptap team releases a new version all packages have the same version number. Grouping all packages to the same version makes it much easier for us to update tiptap packages.
Dependabot now upgrades all official Tiptap packages in on single PR, instead of each package in a separate PR.
The only way to test that is to merge this PR and see if it really works.
> ci: group tiptap packages when updating dependencies

- packages/component-library/src/components/overlay/mt-modal/mt-modal.mdx
- packages/icon-kit/tsconfig.json
I added some documentation for the Modal component(s).
We do not properly communicate how to use the modal. Adding documentation helps developers understand how the component should be used.
I added some docs, which you can view by checking out the Storybook instance.
> Add docs for modal

- packages/component-library/eslint.config.mjs
- packages/component-library/src/components/context-menu/mt-context-menu.spec.ts
- packages/component-library/src/components/form/mt-button/mt-button.spec.ts
- packages/component-library/src/components/form/mt-email-field/mt-email-field.spec.ts
- packages/component-library/src/components/form/mt-textarea/mt-textarea.spec.ts
- packages/component-library/src/components/form/mt-url-field/mt-url-field.spec.ts
- packages/component-library/src/components/navigation/mt-link/mt-link.spec.ts
Adding a linting rule to warn developers about using the Vue test utils
The vue test utils make it very easy to test implementation details. Testing implementation details slows down development massively.
Instead of using the Vue test utils, use the Vue testing library. It's designed to encourage writing tests that speed up development instead of slowing it down.
I added a linting rule to warn user about not using the Vue Test Utils. I decided not to set the level to `error`, because then we would need to migrate all tests at once.
> build(component-library): forbid using @vue/test-utils

- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
Updates the background color of the checkbox.
With the old color, it looked like the input was disabled. This is no longer the case with the new color.
I just updated the token.
You can test the changes by checking out the visual tests.
> fix(component-library): update background color of checkbox

- packages/icon-kit/package.json
- packages/icon-kit/src/figma/index.ts
- packages/icon-kit/src/figma/util/index.ts
- packages/icon-kit/src/index.ts
- packages/icon-kit/tsconfig.json
- pnpm-lock.yaml
This PR fixes the icon kit script.
I changed the tsconfig.json while upgrading the icon kit to ESLint v9. That caused the icon kit to fail. 
I updated the tsconfig, so the build script works and we can execute the script.
I tested the script locally, once we merge it we can sync the new icons from Figma to this repo.
I also upgraded Typescript from v4 to v5 for the icon kit.
> Fix icon kit script

- packages/prettier-config/package.json
This PR fixes the failing provenance check in our release pipeline.
Provenance proofs that the package is really coming from us, and not a potentially malicious developer.
I updated the `repository.url` config for the `@shopware-ag/meteor-prettier-config` package.
The only wait to test it is to merge it and wait for the next release.
> Fix provenance for prettier config

- .changeset/proud-worms-bake.md
- packages/component-library/src/components/form/mt-button/mt-button.vue
This PR fixes a regression regarding the button component.
I implemented a change to center the content of buttons using display grid, but that broke things.
I changed the display mode from `grid` to `inline-grid`
> fix(component-library): change display mode of mt-button to inline-grid

- .changeset/little-moose-accept.md
- docs/admin-sdk/docs/guide/2_api-reference/context.md
- packages/admin-sdk/package.json
- packages/admin-sdk/src/context/compare-version.spec.ts
- packages/admin-sdk/src/context/compare-version.ts
- packages/admin-sdk/src/context/index.ts
- packages/admin-sdk/src/message-types.ts
- pnpm-lock.yaml
This PR adds the logic for compare Shopware version directly in SDK
To make it compatible with any version of Shopware
the comparison is done directly in the SDK
Added test for the comparison logic
> feat: add compare Shopware Version logic directly in the SDK

- .github/workflows/tests.yml
Remove the auto-commit action in the static analysis job.
It creates more issues that it tries to solve.
I just removed the auto-commit action.
To test that, we would need to add a fixable linting error to the codebase and see if the PR does not automatically add a new commit.
> ci: remove auto commit after static analysis

- .changeset/clear-suits-sneeze.md
- README.md
- packages/component-library/README.md
- packages/component-library/src/components/form/mt-password-field/mt-password-field.spec.ts
- packages/component-library/src/components/form/mt-password-field/mt-password-field.vue
- Key ENTER will throw a submit event on the input password
- Added `click.prevent` to not toggle button on bubble
https://github.com/shopware/shopware/issues/7523
- We need this PR merged
- And [the one](https://github.com/shopware/shopware/pull/7664) in the Platform to make everything work
- I think it is a security issue to have all the JS (from every plugin/app) on the login page
> fix: password flickering on submit

- packages/component-library/.storybook/main.ts
This PR simplifies the Storybook config.
This simplifies the storybook configuration. Storybook is also able to load the Add-ons just by a string value.
Additionally, there's an issue when you're on node v23. When you want to start Storybook it fails because it can't find require
I just removed the `getAbsolutePath` function
I did some manual testing to make sure things work the same.
> build(component-library): get rid of node in storybook config

- .changeset/many-cars-join.md
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
Added label slot to the mt-checkbox component to be able to provide complex templates where simple label is not enough.
It's needed to fix https://github.com/shopware/shopware/issues/7471
```
<mt-checkbox ... >
<template #label>
<a href="#">Custom link</a>
</template>
</mt-checkbox>
```
> added label slot to the mt-checkbox component

- packages/component-library/src/components/table-and-list/mt-data-table/sub-components/mt-data-table-settings/mt-data-table-settings.vue
Removes the useless style tag from the `mt-data-table-settings` component.
The styles for the component added some unnecessary size to the bundle output.
The component had a style tag with a single empty selector.
I just removed the style tag
If the visual tests pass, everything is ok.
> Migrate mt data table settings over to plain css

- packages/component-library/src/components/context-menu/mt-context-menu-divider/mt-context-menu-divider.vue
This PR migrates the `mt-context-menu-divider` over to plain css.
SCSS does not provide much, if even at all, value for us.
I migrated the SCSS to plain CSS.
If the visual tests pass everything is fine.
> Migrate mt context menu divider

- .changeset/plenty-drinks-exercise.md
- packages/stylelint-plugin-meteor/package.json
This PR includes the source code for the rules when releasing the package.
Without this change, the plugin only works inside the monorepo. Teams weren't able to use this plugin outside of the monorepo. This was because the `dist` directory would not be published when releasing the package.
I included the `dist` directory in `files` option of the `package.json` file
I tested the changes using `yalc`. I was able to use the package inside another project.
> Include dist in stylelint plugin

- .changeset/serious-snails-accept.md
- packages/stylelint-plugin-meteor/src/rules/prefer-font-token/index.ts
- packages/stylelint-plugin-meteor/src/rules/prefer-font-token/prefer-font-token.test.ts
Adds a auto-fixer for the font-weight properties.
This makes it easier for teams to adopt the Design Tokens.
We can be pretty sure that a weight of `400` maps to `--font-weight-regular`, because those values are standardised values in the design and development world.
When the rule finds a `font-weight` property with a hard-coded number value it tries to find the corresponding Design Token.
I added some unit tests to make sure the changes work as expected.
> feat(stylelint-plugin-meteor): add auto-fixer for font-weights

- .changeset/few-terms-doubt.md
- packages/stylelint-plugin-meteor/src/rules/prefer-border-token/index.ts
- packages/stylelint-plugin-meteor/src/rules/prefer-border-token/prefer-border-token.test.ts
This PR adds an auto-fixer to the stylelint plugin for border radius values.
This makes it easier for teams to adopt the Design Tokens
I've update the rule so it replaces a border radius of:
`50%` -> `var(--border-radius-round)`
`0px` -> `var(--border-radius-none)`
> feat(stylelint-plugin-meteor): add auto-fixer for border-radius values

- .changeset/twenty-poets-know.md
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
This PR removes a duplicate `isInherited` in the `mt-checkbox` component.
The component has a prop and a computed property called `isInherited`. That caused the code to break, because Vue does not know how which one to use.
I renamed the computed property to `isInheritedComputed`
> fix(component-library): get rid of duplicate isInherited

- .changeset/old-owls-give.md
- packages/component-library/src/components/form/mt-switch/mt-switch.vue
Adds a `mt-switch--disabled` class to the `mt-switch` component when the switch is disabled.
This allows developers to query all disabled switch components.
I added a `mt-switch--disabled` class to the 
You can checkout the Storybook branch preview below.
> fix(component-library): add mt-switch--disabled class to mt-switch

- packages/icon-kit/package.json
Removes the pre-publish script from the icon kit.
This script causes the release job to fail, because it's calling a build script which no longer exists and is no longer needed.
There's no longe a need for a pre-publish command because the whole icon automation is done via GitHub workflows.
> build(@shopware-ag/meteor-icon-kit): remove prepublish script

- .changeset/rude-planes-cheat.md
- packages/component-library/src/components/form/mt-datepicker/mt-datepicker.vue
Closes #603
The class name of the hint inside mt-datepicker lacked specificity 
I've renamed 'field-hint' to 'mt-datepicker__hint'
> fix: hint class inside mt-datepicker

- .changeset/flat-queens-explain.md
- .changeset/fresh-cooks-flow.md
- packages/component-library/src/components/form/mt-number-field/mt-number-field.interactive.stories.ts
- packages/component-library/src/components/form/mt-number-field/mt-number-field.spec.ts
- packages/component-library/src/components/form/mt-number-field/mt-number-field.vue
This PR stop the `mt-number-field` from emitting the `change` event twice.
a) Listening on the change event was practically unusable.
It first emitted the newly entered value, after that it instantly emitted the standard HTML change event. Creating the bug described in shopware/shopware#8940
b) This aligns with the standard HTML convention
When the user blurs the input, it no longer emits the `change` event twice.
I've written in TTD style, to make sure the changes work as expected.
Closes shopware/shopware#8940
I did not want to change the API in the past, because it's breaking change. I no longer agree to this and would like to remove the event. Right now, it's broken and does not work anyway. Why keep and API that does not work anyway?
Do you see any issues with this move @jleifeld ?
> fix(component-library): only emit change event when using @change on mt-number-field

- docs/admin-sdk/docs/guide/2_api-reference/composables/useRepository.md
- packages/admin-sdk/src/data/composables/index.ts
- packages/admin-sdk/src/data/composables/useRepository.spec.ts
- packages/admin-sdk/src/data/composables/useRepository.ts
- packages/admin-sdk/src/data/repository-adapter.spec.ts
- packages/admin-sdk/src/data/repository-adapter.ts
- packages/admin-sdk/src/data/repository.ts
Added `useRepository` composable with supporting adapter and tests for simplified repository access in Vue components.
- Simplifies repository usage in Vue components
- Improves performance through lazy loading
- Standardizes behavior across repository implementations
- Enhances developer experience
Three ways to obtain repositories: props, dependency injection, or lazy loading fallback, with an adapter to normalize interfaces.
Complete test coverage for initialization paths, methods, sync/async sources, and edge cases.
Change the `clone` parameters order in the SDK repository to mimic Platform repository, maintaining backward compatibility
> feat: add useRepository composable

- packages/component-library/src/components/form/_internal/mt-base-field/mt-base-field.vue
Changing the padding in the field addition when there is a button inside.
Because the issue with the button size described [here](https://github.com/shopware/shopware/issues/10048)
checking with CSS if the addition has a button or not, and removing the container padding and adding it to the button
> fix: padding and size for buttons inside field addition

- packages/component-library/src/components/table-and-list/mt-data-table/composables/useScrollPossibilitiesClasses.spec.ts
- packages/component-library/src/components/table-and-list/mt-data-table/composables/useScrollPossibilitiesClasses.ts
- packages/component-library/src/components/table-and-list/mt-data-table/mt-data-table.vue
This PR hides the scroll shadow when displaying an empty state for the data table.
A shadow tells the user that they can scroll. But you can't scroll when there's not content. 
This confuses the user and we should hide the scroll shadow.
I've updated the `useScrollPossbilities` class so that it no longer shows a scroll indicator when we show an empty state.
I've added a unit test to make sure it works. Moreover, I've we have some visual tests in place, to make sure everything works as expected.
> hide scroll shadow in data table when showing an empty state

- .changeset/quick-dolls-trade.md
- packages/component-library/src/components/form/_internal/mt-field-error/mt-field-error.spec.ts
- packages/component-library/src/components/form/_internal/mt-field-error/mt-field-error.vue
This pr fixes the bug that some validation errors were missing or incorrect in meteor components. 
In platform when the page was translated some validation errors were appearing in English or in some cases not at all.
I've added logic to check global.error-codes then mt-field-errors and if nothing matches, we fall back to the default behaviour.
I've added some unit tests but also tested this in admin
> fix: missing validation errors

- packages/component-library/src/components/overlay/mt-tooltip/mt-tooltip.vue
`b` and `i` serve a different purpose than `strong` and `i`.
In terms of accessibility, you mostly want to use `strong` and `em`
Extend the tag stripper
https://github.com/shopware/shopware/pull/10949
> feat(a11y): Allow `strong` and `em` html tags

- .changeset/blue-pigs-grow.md
- .changeset/clean-teachers-develop.md
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.spec.ts
- packages/component-library/src/components/form/mt-checkbox/mt-checkbox.vue
I've added a couple of unit tests for the `mt-checkbox` component.
With more unit tests we can be more confident that the components work they way we want it to work.
I've written some unit test.
I've added a couple of unit tests.
I fixed two bugs, while testing the component:
1. It's now possible to set a `name` for the checkbox
2. Now, you can mark the checkbox as required
> Add tests for the checkbox component

- .changeset/tasty-peas-juggle.md
- .changeset/three-buttons-scream.md
- packages/component-library/src/components/layout/mt-empty-state/mt-empty-state.vue
I set the height and width for the icon always to 48px. It has now the same height and width as it is in Figma.
The size of the gray area, for the icon, changed when you use a different icon. When you used one icon it was 42px large. If you used another icon it might be 46px tall and 43px wide.
We need to get rid of that inconsistency.
I defined a fixed height and width for the icon section. Now it's always 48px tall and wide.
The visual tests make sure everything still looks fine.
I've made sure the empty state description no longer shows any widows, when the texts needs to wrap.
> Fix visual bugs for empty state

- .github/workflows/tests.yml
- package.json
- scripts/validate-changesets.js
I added a script that validates the package names in each changeset. It makes sure the defined packages actually exist.
This script acts a early-warning.
We had a case where the package name, in a changeset was incorrect, it specified a package which did not exit. 
This broke the release pipeline. 
I added script in `.scripts/`. The CI runs that script every time we create a new PR.
I've tested the changes manually. 
I decided not to create an automated tests for this, because this is some trivial code. It's not part of any product and serves as a minor helper in our daily work.
> CI: validate package names in changesets
